TRANSLATIONS = {
    "en": {
        "app_name": "EduReach",
        "tagline": "Remote Classroom Platform",
        "dashboard": "Dashboard",
        "courses": "Courses",
        "login": "Login",
        "signup": "Sign Up",
        "logout": "Logout",
        "email": "Email",
        "password": "Password",
        "name": "Name",
        "role": "Role",
        "teacher": "Teacher",
        "student": "Student",
        "create_course": "Create Course",
        "course_name": "Course Name",
        "subject": "Subject",
        "description": "Description",
        "materials": "Materials",
        "upload_material": "Upload Material",
        "assignments": "Assignments",
        "create_assignment": "Create Assignment",
        "title": "Title",
        "deadline": "Deadline",
        "submit": "Submit",
        "submissions": "Submissions",
        "download": "Download",
        "announcements": "Announcements",
        "post_announcement": "Post Announcement",
        "message": "Message",
        "attendance": "Attendance",
        "mark_attendance": "Mark Attendance",
        "present": "Present",
        "absent": "Absent",
        "quiz": "Quiz",
        "take_quiz": "Take Quiz",
        "question": "Question",
        "option_a": "Option A",
        "option_b": "Option B",
        "option_c": "Option C",
        "option_d": "Option D",
        "correct_option": "Correct Option",
        "create_quiz": "Create Quiz",
        "add_question": "Add Question",
        "existing_questions": "Existing Questions",
        "correct_answer": "Correct answer",
        "quiz_available": "Quiz Available",
        "questions": "questions",
        "take_quiz_for": "Take quiz for",
        "no_quiz": "No quiz available yet for this course.",
        "score": "Score",
        "total": "Total",
        "percentage": "Percentage",
        "enroll": "Enroll",
        "enrolled": "Enrolled",
        "enrolled_courses": "Enrolled Courses",
        "my_courses": "My Courses",
        "badges": "Badges",
        "recommendations": "Recommendations",
        "flagged_students": "Flagged Students",
        "performance": "Performance",
        "welcome": "Welcome",
        "back": "Back",
        "save": "Save",
        "cancel": "Cancel",
        "edit": "Edit",
        "delete": "Delete",
        "view": "View",
        "no_courses": "No courses available",
        "no_materials": "No materials uploaded yet",
        "no_assignments": "No assignments created yet",
        "no_announcements": "No announcements yet",
        "file": "File",
        "uploaded_at": "Uploaded At",
        "submitted_at": "Submitted At",
        "graded": "Graded",
        "pending": "Pending",
        "students": "Students",
        "quick_actions": "Quick Actions",
        "learning_progress": "Learning Progress",
        "attendance_rate": "Attendance Rate",
        "achievements": "Achievements",
        "recommended_for_you": "Recommended for You",
        "need_help": "Need Help?",
        "contact_teacher": "Contact Teacher",
        "all_fields_required": "All fields are required",
        "invalid_credentials": "Invalid email or password",
        "email_exists": "Email already exists",
        "registration_success": "Registration successful. Please login.",
        "login_success": "Login successful",
        "logout_success": "You have been logged out",
        "enrollment_success": "Successfully enrolled in course",
        "upload_success": "File uploaded successfully",
        "submission_success": "Assignment submitted successfully",
        "attendance_marked": "Attendance marked successfully",
        "announcement_posted": "Announcement posted successfully",
        "quiz_submitted": "Quiz submitted successfully",
    },
    "te": {
        "app_name": "ఎడ్యురీచ్",
        "tagline": "రిమోట్ క్లాస్రూమ్ ప్లాట్‌ఫారమ్",
        "dashboard": "డాష్‌బోర్డ్",
        "courses": "కోర్సులు",
        "login": "లాగిన్",
        "signup": "సైన్ అప్",
        "logout": "లాగౌట్",
        "email": "ఇమెయిల్",
        "password": "పాస్‌వర్డ్",
        "name": "పేరు",
        "role": "పాత్ర",
        "teacher": "ఉపాధ్యాయుడు",
        "student": "విద్యార్థి",
        "create_course": "కోర్సు సృష్టించండి",
        "course_name": "కోర్సు పేరు",
        "subject": "విషయం",
        "description": "వివరణ",
        "materials": "మెటీరియల్స్",
        "upload_material": "మెటీరియల్ అప్‌లోడ్ చేయండి",
        "assignments": "అసైన్‌మెంట్స్",
        "create_assignment": "అసైన్‌మెంట్ సృష్టించండి",
        "title": "శీర్షిక",
        "deadline": "గడువు",
        "submit": "సమర్పించండి",
        "submissions": "సమర్పణలు",
        "download": "డౌన్‌లోడ్",
        "announcements": "ప్రకటనలు",
        "post_announcement": "ప్రకటన పోస్ట్ చేయండి",
        "message": "సందేశం",
        "attendance": "హాజరు",
        "mark_attendance": "హాజరు గుర్తించండి",
        "present": "హాజరు",
        "absent": "గైర్హాజరు",
        "quiz": "క్విజ్",
        "take_quiz": "క్విజ్ తీసుకోండి",
        "question": "ప్రశ్న",
        "option_a": "ఎంపిక A",
        "option_b": "ఎంపిక B",
        "option_c": "ఎంపిక C",
        "option_d": "ఎంపిక D",
        "correct_option": "సరైన ఎంపిక",
        "create_quiz": "క్విజ్ సృష్టించండి",
        "add_question": "ప్రశ్న జోడించండి",
        "existing_questions": "ఉన్న ప్రశ్నలు",
        "correct_answer": "సరైన సమాధానం",
        "quiz_available": "క్విజ్ అందుబాటులో ఉంది",
        "questions": "ప్రశ్నలు",
        "take_quiz_for": "క్విజ్ తీసుకోండి",
        "no_quiz": "ఈ కోర్సుకు ఇంకా క్విజ్ అందుబాటులో లేదు.",
        "score": "స్కోర్",
        "total": "మొత్తం",
        "percentage": "శాతం",
        "enroll": "ఎన్రోల్",
        "enrolled": "ఎన్రోల్ చేయబడింది",
        "enrolled_courses": "ఎన్రోల్ చేసిన కోర్సులు",
        "my_courses": "నా కోర్సులు",
        "badges": "బ్యాడ్జిలు",
        "recommendations": "సిఫార్సులు",
        "flagged_students": "ఫ్లాగ్ చేయబడిన విద్యార్థులు",
        "performance": "ప్రదర్శన",
        "welcome": "స్వాగతం",
        "back": "వెనుక",
        "save": "సేవ్",
        "cancel": "రద్దు",
        "edit": "ఎడిట్",
        "delete": "డిలీట్",
        "view": "వీక్షించండి",
        "no_courses": "కోర్సులు అందుబాటులో లేవు",
        "no_materials": "ఇంకా మెటీరియల్స్ అప్‌లోడ్ చేయబడలేదు",
        "no_assignments": "ఇంకా అసైన్‌మెంట్స్ సృష్టించబడలేదు",
        "no_announcements": "ఇంకా ప్రకటనలు లేవు",
        "file": "ఫైల్",
        "uploaded_at": "అప్‌లోడ్ చేసిన సమయం",
        "submitted_at": "సమర్పించిన సమయం",
        "graded": "గ్రేడ్ చేయబడింది",
        "pending": "పెండింగ్",
        "students": "విద్యార్థులు",
        "quick_actions": "త్వరిత చర్యలు",
        "learning_progress": "లెర్నింగ్ పురోగతి",
        "attendance_rate": "హాజరు రేటు",
        "achievements": "సాధనలు",
        "recommended_for_you": "మీకు సిఫార్సు చేయబడింది",
        "need_help": "సహాయం కావాలా?",
        "contact_teacher": "ఉపాధ్యాయుడిని సంప్రదించండి",
        "all_fields_required": "అన్ని ఫీల్డ్స్ అవసరం",
        "invalid_credentials": "చెల్లని ఇమెయిల్ లేదా పాస్‌వర్డ్",
        "email_exists": "ఇమెయిల్ ఇప్పటికే ఉంది",
        "registration_success": "నమోదు విజయవంతం. దయచేసి లాగిన్ చేయండి.",
        "login_success": "లాగిన్ విజయవంతం",
        "logout_success": "మీరు లాగౌట్ అయ్యారు",
        "enrollment_success": "కోర్సులో విజయవంతంగా ఎన్రోల్ అయ్యారు",
        "upload_success": "ఫైల్ విజయవంతంగా అప్‌లోడ్ అయ్యింది",
        "submission_success": "అసైన్‌మెంట్ విజయవంతంగా సమర్పించబడింది",
        "attendance_marked": "హాజరు విజయవంతంగా గుర్తించబడింది",
        "announcement_posted": "ప్రకటన విజయవంతంగా పోస్ట్ చేయబడింది",
        "quiz_submitted": "క్విజ్ విజయవంతంగా సమర్పించబడింది",
    },
    "hi": {
        "app_name": "एड्युरीच",
        "tagline": "रिमोट क्लासरूम प्लेटफार्म",
        "dashboard": "डैशबोर्ड",
        "courses": "पाठ्यक्रम",
        "login": "लॉगिन",
        "signup": "साइन अप",
        "logout": "लॉगआउट",
        "email": "ईमेल",
        "password": "पासवर्ड",
        "name": "नाम",
        "role": "भूमिका",
        "teacher": "शिक्षक",
        "student": "छात्र",
        "create_course": "पाठ्यक्रम बनाएं",
        "course_name": "पाठ्यक्रम का नाम",
        "subject": "विषय",
        "description": "विवरण",
        "materials": "सामग्री",
        "upload_material": "सामग्री अपलोड करें",
        "assignments": "असाइनमेंट्स",
        "create_assignment": "असाइनमेंट बनाएं",
        "title": "शीर्षक",
        "deadline": "समय सीमा",
        "submit": "सबमिट करें",
        "submissions": "सबमिशन्स",
        "download": "डाउनलोड",
        "announcements": "घोषणाएं",
        "post_announcement": "घोषणा पोस्ट करें",
        "message": "संदेश",
        "attendance": "उपस्थिति",
        "mark_attendance": "उपस्थिति चिह्नित करें",
        "present": "उपस्थित",
        "absent": "अनुपस्थित",
        "quiz": "क्विज",
        "take_quiz": "क्विज लें",
        "question": "प्रश्न",
        "option_a": "विकल्प A",
        "option_b": "विकल्प B",
        "option_c": "विकल्प C",
        "option_d": "विकल्प D",
        "correct_option": "सही विकल्प",
        "create_quiz": "क्विज बनाएं",
        "add_question": "प्रश्न जोड़ें",
        "existing_questions": "मौजूदा प्रश्न",
        "correct_answer": "सही उत्तर",
        "quiz_available": "क्विज उपलब्ध",
        "questions": "प्रश्न",
        "take_quiz_for": "क्विज लें",
        "no_quiz": "इस पाठ्यक्रम के लिए अभी तक कोई क्विज उपलब्ध नहीं है।",
        "score": "स्कोर",
        "total": "कुल",
        "percentage": "प्रतिशत",
        "enroll": "नामांकन",
        "enrolled": "नामांकित",
        "enrolled_courses": "नामांकित पाठ्यक्रम",
        "my_courses": "मेरे पाठ्यक्रम",
        "badges": "बैज",
        "recommendations": "सिफारिशें",
        "flagged_students": "चिह्नित छात्र",
        "performance": "प्रदर्शन",
        "welcome": "स्वागत",
        "back": "वापस",
        "save": "सेव",
        "cancel": "रद्द",
        "edit": "एडिट",
        "delete": "डिलीट",
        "view": "देखें",
        "no_courses": "कोई पाठ्यक्रम उपलब्ध नहीं",
        "no_materials": "अभी तक कोई सामग्री अपलोड नहीं की गई",
        "no_assignments": "अभी तक कोई असाइनमेंट नहीं बनाया गया",
        "no_announcements": "अभी तक कोई घोषणा नहीं",
        "file": "फाइल",
        "uploaded_at": "अपलोड किया गया",
        "submitted_at": "सबमिट किया गया",
        "graded": "ग्रेडेड",
        "pending": "पेंडिंग",
        "students": "छात्र",
        "quick_actions": "त्वरित कार्रवाई",
        "learning_progress": "सीखने की प्रगति",
        "attendance_rate": "उपस्थिति दर",
        "achievements": "उपलब्धियां",
        "recommended_for_you": "आपके लिए सिफारिश",
        "need_help": "मदद चाहिए?",
        "contact_teacher": "शिक्षक से संपर्क करें",
        "all_fields_required": "सभी फील्ड्स आवश्यक हैं",
        "invalid_credentials": "अमान्य ईमेल या पासवर्ड",
        "email_exists": "ईमेल पहले से मौजूद है",
        "registration_success": "पंजीकरण सफल। कृपया लॉगिन करें।",
        "login_success": "लॉगिन सफल",
        "logout_success": "आप लॉगआउट हो गए हैं",
        "enrollment_success": "पाठ्यक्रम में सफलतापूर्वक नामांकित",
        "upload_success": "फाइल सफलतापूर्वक अपलोड हुई",
        "submission_success": "असाइनमेंट सफलतापूर्वक सबमिट हुआ",
        "attendance_marked": "उपस्थिति सफलतापूर्वक चिह्नित",
        "announcement_posted": "घोषणा सफलतापूर्वक पोस्ट की गई",
        "quiz_submitted": "क्विज सफलतापूर्वक सबमिट हुआ",
    }
}

DEFAULT_LANG = "en"

def get_text(key, lang=None):
    if lang is None:
        lang = DEFAULT_LANG
    return TRANSLATIONS.get(lang, TRANSLATIONS[DEFAULT_LANG]).get(key, key)

def get_available_languages():
    return {
        "en": "English",
        "te": "తెలుగు (Telugu)",
        "hi": "हिन्दी (Hindi)"
    }
